알림 페이지 추가
Nexters/BRUNO pull request #76
Opened 2022-04-21 14:44 UTC by sbyeol3

## Issue 📃

## Changes 🧑‍💻

<img width="290" alt="스크린샷 2022-04-21 오후 11 41 42" src="https://user-images.githubusercontent.com/43198553/164483746-e963b9c5-06c5-44d8-9f40-ce640e313d4e.png">

## Points 👀

- 헤더가 피그마랑 조금 다르긴 한데 기능적으로는 차이가 없어서 ㅠ.... 일단 패스
- 무한스크롤 해야되는데 서버가 페이징 기능을 안넣어놨길래 일단 데이터 많이 불러오는 걸로 대체해둠...
- 데이터도 날짜별로 안되어 있어서 useMemo로 분류해둠

2022-04-21 17:08 UTC, sewonkimm requested changes
판매 아이콘만 변경하면 될 듯!

2022-04-21 17:08 UTC, sewonkimm commented on src/components/NotificationSection/NotificationItem.tsx
> +        <NotificationIcon />
판매일 때에는 Icon이 다름!

![image](https://user-images.githubusercontent.com/30452963/164513164-822b597c-92ad-412a-b367-f205434269b4.png)

2022-04-21 17:08 UTC, sewonkimm commented on src/pages/NotificationPage/NotificationPage.tsx
> +      const dateString = date.toISOString().substring(0, 10);
오 moment 같은거 안써도 이렇게 뽑아내는 방법이 있구나... 👀

2022-04-23 07:17 UTC, sbyeol3 commented on src/components/NotificationSection/NotificationItem.tsx
> +        <NotificationIcon />
어딨는겨 ㅠㅠ @sewonkimm

2022-04-23 07:33 UTC, merged

2022-04-23 11:02 UTC, sewonkimm commented on src/components/NotificationSection/NotificationItem.tsx
> +        <NotificationIcon />
https://www.figma.com/file/xcrMpNXNRnJ4oDLbPskVMD/Cookie_pang_Design_2%EC%B0%A8%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8?node-id=2%3A10465 요있다